import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";
import NextTopLoader from "nextjs-toploader";

import { Sora, Poppins, Inter } from "next/font/google";
import { ChatBot } from "@/components/chatbot/chat-bot";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["400", "500", "600", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Kashhussain Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${sora.variable} ${poppins.variable} ${inter.variable}`}
    >
      <body>
        <NextTopLoader color="#1E3A8A" height={3} showSpinner={false} />
        <AuthProvider>
          <AppProvider>
            {children}

            <Toaster />
            <ChatBot />
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
